language: python

python:
  - 3.4

cache: pip
sudo: required

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install --upgrade setuptools

branches:
 only:
  - master
  - develop

script: coverage run --omit=/**env/** manage.py test

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
