language: python

python:
  - 3.4

cache: pip
sudo: required

install:
  - pip install -r requirements.txt
  - pip install coverage

branches:
 only:
  - master

script: coverage run --omit=/**env/** manage.py test

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls